name: Generate API Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install Redoc CLI
        run: npm install -g redoc-cli

      - name: Generate API documentation
        run: redoc-cli bundle ./api/latest.yaml -o ./docs/index.html

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ./docs/index.html
          git commit -m 'docs(api): generate HTML documentation from OpenAPI spec'
          git push
